version: "3.7"

services:
  db:
    image: yobasystems/alpine-mariadb
    container_name: konakore-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=please_change
      - MYSQL_DATABASE=konakore
    ports:
      - "3307:3306"
    volumes:
      - /opt/konakore/db:/var/lib/mysql

  server:
    image: zeroalcbeer/konakore-web:latest
    container_name: konakore-web
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - /mnt/hd1/Wallpaper:/wallpaper
      - /opt/konakore:/assets
    ports:
      - "7079:80"
    environment:
      dsn: "root:please_change@tcp(db:3306)/konakore?charset=utf8mb4&parseTime=True&loc=Local"
      sync_spec: "0 */2 * * *" # every 2 hours
      proxy: "socks5://192.168.0.110:7891"
      cookies: ""
