#  docker buildx bake -f docker-bake.yaml --push
version: "3.4"
services:
  server:
    build:
      dockerfile: cmd/server/Dockerfile
    image: cheerchen37/konakore-web
  syncer:
    build:
      dockerfile: cmd/syncer/Dockerfile
    image: cheerchen37/konakore-syncer

